### PR TITLE
Split promo URs from normal URs in the user page

### PR DESCRIPTION
**Pull request by Vazkii**
Also added an oxford comma because I'm cool like that.

This is my first time working with python for anything proper, and first time working with django at all, so if I broke something I'm sorry :<

**Before/After:**
ss 2017-03-08 at 10 36 09
ss 2017-03-08 at 11 17 04

(ignore the change in spacing, it only happened because the screenshots were taken at different resolutions)

### CODE REVIEW

**Comment by rdsathene** [comment]
Thanks for fixing the space before the comma following SR - that was my mistake. If we're going to pull promos out of URs, shouldn't we do it with SRs too?

**Comment by Vazkii** [comment]
Perhaps having a separate line for promos would be better? Just to keep the
Significant Cards line less cluttered.

**Comment by rdsathene** [comment]
Agreed, although it's probably best to get db0 in on that consensus.

**Comment by Vazkii** [comment]
Any update on this?

**Pull request closed without merging**
